services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 astralnova-backend astralnova-frontend
    restart: unless-stopped
